### ISSUE TITLE
Hue Addon

### ISSUE THREAD

**Issue by jensfr1** [Zefau/ioBroker.nello#11]
Hi, 
I used the HUE addon you have posted in the description. It works well. Thanks a lot! 
 Just a suggestion. 

- Get the light status (on,off, color)  before the alarm on the lamp is activated and set back to the prior status once it is completed. 

I was watching TV, then it turned green and then light went off so I had to turn it on again and change the color. 

Thanks, Jens

**Comment by Zefau** [comment]
Thanks for the feedback. I added the functionality. Please test and report back if it works correctly.

Thanks,
Zefau

**Comment by jensfr1** [comment]
Getting an error:

```
20.1.2019, 18:20:07.679	[info ]: javascript.0 Stop script script.js.common.turnlight
20.1.2019, 18:20:07.724	[info ]: javascript.0 Start javascript script.js.common.turnlight
20.1.2019, 18:20:07.725	[info ]: javascript.0 script.js.common.turnlight: registered 1 subscription and 0 schedules
20.1.2019, 18:20:10.332	[error]: javascript.0 script.js.common.turnlight: The "getState" method cannot be used synchronously, because the adapter setting "Do not subscribe to all states on start" is enabled.
20.1.2019, 18:20:10.333	[error]: javascript.0 script.js.common.turnlight: Please disable that setting or use "getState" with a callback, e.g.: getState("hue.1.Philips_hue.TV_Licht.on", (err, state) => { ... });
20.1.2019, 18:20:10.333	[error]: javascript.0     at script.js.common.turnlight:79:108
20.1.2019, 18:20:10.333	[error]: javascript.0     at script.js.common.turnlight:79:29
20.1.2019, 18:20:10.333	[error]: javascript.0     at colors (script.js.common.turnlight:75:13)
20.1.2019, 18:20:10.333	[error]: javascript.0     at Object.<anonymous> (script.js.common.turnlight:23:9)
```

**Comment by Zefau** [comment]
You have activated the checkbox `Do not subscribe to all states on start` in the ioBroker.javascript adapter settings. Untick the checkbox and try again.

**Comment by jensfr1** [comment]
Still getting this? 
1/21/2019, 7:42:03 PM.199	[error]: javascript.0     at Object.<anonymous> (script.js.common.turnlight:23:9)

In the adapter for JS I have activated  SetObject and Exec.  Alexa is working fine!

**Comment by Zefau** [comment]
What code line is in row 23 (`script.js.common.turnlight:23:9`)?

**Comment by jensfr1** [comment]
Sorry for my error report. The issue is sitting in front of the laptop.. It works fine. Just tried it. Code was not in global but in common area. :-) Funktioniert echt super!!!

**Comment by Zefau** [comment]
perfect :)
