### ISSUE TITLE
Repository broken!! Link invalid because of branch change!

### ISSUE THREAD

**Issue by Apollon77** [Zefau/ioBroker.nello#13]
see https://travis-ci.org/ioBroker/ioBroker.repositories/builds/484823011?utm_medium=notification&utm_source=email ... In the Repo the link goes to "master" which is not existing anymore.

Please fix ASAP!!

**Comment by Zefau** [comment]
Sorry for the issue. Fixed with https://github.com/ioBroker/ioBroker.repositories/pull/297.

**Comment by Apollon77** [comment]
Please fix also stable links
