### ISSUE TITLE
kein Eintrag in iot.0.services

### ISSUE THREAD

**Issue by mondface** [Zefau/ioBroker.nello#16]
Hallo,
die Schnellinstallation war bei mir erfolgreich, sehe ich auch daran, dass eine neu erzeugte Timeline unter objects angezeigt wird.
Bei der erweiterte Installation mit iot seh ich aber kein Eintrag für iot.0.services, den ich ja dann in  "ioBroker.iot nello Objekt" eintragen soll.

für das login von iot habe ich einem iobroker pro benutzer "mail@gmail.com"
nello in whitelist
und die url ala https://service.iobroker.in/v1/iotService?key=<API_KEY>&user=<EMAIL>&service=custom_<SERVICE_NAME> 
in die nello instance eingetragen.
Gehe ich dann auf  iot.0.services in objects, steht da nichts...

lot und nello instanzen sind grün.
Gruß
frAnk

**Comment by Zefau** [comment]
Nach dem Setup einfach mal klingeln, dann wird der State angelegt. Ich aktualisiere die Dokumentation nachher nochmal und füge auch mal paar Screenshots ein.

**Comment by mondface** [comment]
habe geklingelt, keine Änderung...

**Comment by Zefau** [comment]
So, habe die Anleitung um Screenshots ergänzt und etwas präzisiert, siehe https://github.com/Zefau/ioBroker.nello#advanced-setup.
1. Was passiert, wenn du den Link manuell im Browser aufrufst?
2. Was steht im ioBroker Log, wenn du den nello Adapter neu startest? Er sollte den Webhook mit der URL registrieren. Zeigt er das so an? Schick mir ggf. das Log mal zu.

**Comment by mondface** [comment]
hi,
da hat sich wohl mein iobroker merkwürdig verhalten.
Nach Neustart gehts jetzt.
Alexa für Sprachausgabe funktioniert jetzt auch.
Danke für Deine Mühe!
Gruß
frAnk
