### ISSUE TITLE
Error-Log

### ISSUE THREAD

**Issue by Azathoth88** [Zefau/ioBroker.nello#2]
Hallo,
zunächst vielen Dank für deine Arbeit! Das ist ganz großes Kino! Ich hatte die Tage selbst überlegt, ob ich langfristig daran arbeiten könnte. Aber nachdem ich die API gesehen habe, habe ich festgestellt, dass dies doch ein wenig komplexer als gedacht ist.

Den Adapter habe ich in ioBroker installiert. Die Einbindung war einfach. Ich habe kurzzeitig folgende Meldung erhalten, welche sich aber soeben selbst scheinbar gelöst hat. Zumindest läuft der Adapter nun.

Eine Frage habe ich dennoch: Existiert für den Webhook überhaupt ein ioBroker-Adapter, sodass dies funktioniert? Ist der socket.io hier zu verwenden?

host.iobroker | 2018-10-31 22:47:39.402 | error | instance system.adapter.nello.0 terminated with code 0 (OK)
-- | -- | -- | --
host.iobroker | 2018-10-31 22:47:39.402 | error | Caught by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:133:20)
host.iobroker | 2018-10-31 22:47:39.402 | error | Caught by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.iobroker | 2018-10-31 22:47:39.401 | error | Caught by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
host.iobroker | 2018-10-31 22:47:39.401 | error | Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:133:20)
host.iobroker | 2018-10-31 22:47:39.400 | error | Caught by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.iobroker | 2018-10-31 22:47:39.399 | error | Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
host.iobroker | 2018-10-31 22:47:39.399 | error | Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
host.iobroker | 2018-10-31 22:47:39.398 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1784:57)
host.iobroker | 2018-10-31 22:47:39.398 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.nello/main.js:155:12
host.iobroker | 2018-10-31 22:47:39.397 | error | Caught by controller[0]: at Nello.listen (/opt/iobroker/node_modules/iobroker.nello/nello.js:293:15)
host.iobroker | 2018-10-31 22:47:39.397 | error | Caught by controller[0]: TypeError: Cannot read property 'url' of undefined
nello.0 | 2018-10-31 22:47:39.336 | error | uncaught exception: Cannot read property 'url' of undefined

**Comment by Zefau** [comment]
Vielen Dank für den Bug-Report. Der Fehler ist wahrscheinlich dadurch bedingt, dass in der Configuration keine DynDNS IP Adresse angegeben ist (notwendig für Webhooks und das Empfangen von Events).
Der ioBroker adapter ist aktualisiert. Bitte nochmal probieren, ob der Fehler behoben ist.

**Comment by Azathoth88** [comment]
Vielen Dank für dein Feedback. Ich schrieb, dass sich das Thema bei mir selbst gelöst hat. Ich habe hier schon ein wenig experimentiert. Ein Forwarding ebenfalls testweise hinterlegt - das erklärt warum sich das für mich selbst gelöst hat. Der Adapter läuft nun bereits als Adapter in einem VIS-View produktiv.

Saubere Arbeit! Danke!
