### ISSUE TITLE
Token Generierung bleibt stecken

### ISSUE THREAD

**Issue by ghost** [Zefau/ioBroker.nello#3]
Hallo,

habe mit der Version 0.4.3 das Problem dass ich den Token nicht generieren kann (Client ID und Secret kann ich zwar eingeben aber bei Klick auf Neuen Token generieren passiert nichts weiter.

Habe mit Chrome und Firefox getestet ob es ein Browser Issue ist - zeigt in beiden Fällen leider das gleiche Verhalten.

Admin Adapter ist aktuell mit 3.5.10

**Comment by Zefau** [comment]
Vielen Dank für den Hinweis. Ich prüfe das direkt.

**Comment by Zefau** [comment]
Habe das Error-Handling überarbeitet. Könntest du die Github Version über deine lokale Installation einmal drüber installieren und die Token Generierung erneut probieren?
Der Fehler sollte nun aussagekräftiger sein. Sofern es sich um einen 401 Fehler handelt, sind Client ID / Secret falsch.

Viele Grüße
Zefau

**Comment by ghost** [comment]
Hi, das mit dem 401 Fehler war der Auslöser warum ich einen neuen Token generieren wollte weil ich mir das schon dachte.
Passiert leider immer noch nichts beim Klick auf "Neuen Token generieren" - kein zugehöriger Logeintrag - der Adapter läuft ja auch nicht

![image](https://user-images.githubusercontent.com/45273094/48923167-89e3e680-eeac-11e8-865c-861e6ae1ae66.png)

**Comment by Zefau** [comment]
Starte mal den Adapter und gehe dann in die Einstellungen, ob es dann geht.

**Comment by ghost** [comment]
Adapter ist gestartet - Meckert naturgemäß wegen dem Token - beim Klick auf "Neuen Token generieren" passiert gar nichts - der Screen bleibt unverändert stehen.
nello.0 | 2018-11-22 23:43:25.835 | error | Token is missing! Please go to settings and generate a token first!
-- | -- | -- | --

**Comment by Zefau** [comment]
Vielen Dank für die Geduld. Ich finde den Fehler leider nicht. Bei mir funktioniert's wunderbar, auch, wenn ich den Adapter deinstalliere und von Github neu installiere.
Ich habe den Status-Log im Admin Bereich erweitert, so dass nun der aktuelle Status angezeigt wird. Bitte nochmal von Github drüber installieren oder bis morgen warten, dann sollte die Version im ioBroker auf 0.4.5 aktualisiert sein.

Danke und viele Grüße
Zefau

**Comment by Zefau** [comment]
Hattest du Gelegenheit es nochmal zu probieren?

**Comment by ghost** [comment]
Komme erst Sonntag abend dazu. Gebe dann Rückmeldung.

Von meinem Huawei-Mobiltelefon gesendet

**Comment by ghost** [comment]
Hallo - leider unverändertes Verhalten bei Klick auf Neuen Token generieren passiert m.E. nichts - er erzeugt kein Log und auch sonst ist kein Response erkennbar. - Ich habe auch einen zweiten API Account aktiviert dass ich den Fehler auf Seite Nello auschließen kann. Ändert leider auch nichts an dem Verhalten.

Sollte der Adapter wenn Client ID oder Secret falsch sind eine Meldung ausgeben ? Ich kann da irgendwas einfüllen und bekomme im Umkehrschluss auch keine Fehlermeldung

Admin ist aktuell auf 3.5.10 - Host auf 1.4.2

**Comment by Zefau** [comment]
Sieht der Screen bei dir wie folgt aus (insbesondere mit dem "Status" und dem weißen Feld?)

![capture](https://user-images.githubusercontent.com/14368811/48982466-52ab4a80-f0e3-11e8-831a-9e75eba60ca3.PNG)

Kannst du bitte außerdem den Log posten? Links auf "Log" im Menü und dann auf nello filtern und hier rein kopieren. Sonst ist es schwer zu bewerten, woher der Fehler kommt.

Viele Grüße
Zefau

**Comment by ghost** [comment]
Screen sieht interessanterweise nicht so aus - obwohl unter Informationen 0.4.6

Der Status fehlt komplett...

**Comment by ghost** [comment]
Log ist eigentlich nicht Aussagekräftig

nello.0 | 2018-11-25 17:30:32.859 | error | Token is missing! Please go to settings and generate a token first!
-- | -- | -- | --
nello.0 | 2018-11-25 17:30:32.855 | info | starting. Version 0.4.6 in /opt/iobroker/node_modules/iobroker.nello, node: v8.12.0
nello.0 | 2018-11-25 17:25:32.835 | info | cleaned everything up...
nello.0 | 2018-11-25 17:25:32.814 | info | cleaned everything up...

**Comment by ghost** [comment]
Jetzt hab ichs rausgefunden - Hab den Adapter nochmal komplett aus dem ioBroker Adapter Listing rausgeworfen - denke da hat sich was verhakt gehabt - jetzt klappts wieder wunderbar - sorry für die Umstände aber manches mal sucht man sich bei nem Fehler zum Nurmi.

**Comment by Zefau** [comment]
Klasse, freut mich. Viele Grüße
