### ISSUE TITLE
Instance is not working anymore

### ISSUE THREAD

**Issue by Netfreak25** [Zefau/ioBroker.nello#31]
Probably because of the API itself.
But the light is still green, which is irritating.

**Comment by Zefau** [comment]
The API has been shut down and is not reachable. You can easily reproduce this using the nello API website, which is https://nellopublicapi.docs.apiary.io/.

This case of a non-reachable API was never considered and is thus not implemented, which is why the lights won't change.

**Comment by Zefau** [comment]
I added an information to the README page.

Furthermore, I found an interesting article (in German though) on how to free nello from the cloud https://hypfer.de/blog/2018/12/04/wie-man-ein-nello-one-nicht-von-der-cloud-befreit/. It is only a baseline though for further investigation on the API.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.nello/issues/35
