### ISSUE TITLE
Update stable version in repo to 2.0.8

### ISSUE THREAD

**Issue by GermanBluefox** [Zefau/ioBroker.nello#33]
# Think about update stable version to 2.0.8
**Version**: stable=**2.0.6** (228 days old) => latest=**2.0.8** (206 days old)
**Installs**: stable=**71** (57.72%), latest=**41** (33.33%), total=**123**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L853)

**Comment by Zefau** [comment]
See note in the repo and issue https://github.com/Zefau/ioBroker.nello/issues/31: 
> nello API has been shut down. This adapter will thus not work.

This adapter is currently dead until the API will be revived.

**Comment by t6a** [comment]
It might help to contact the new owners of nello (an Italian company). They moved the system on a new server but maybe "forgot" or prioritised the api low

**Comment by Zefau** [comment]
Sure, go ahead :-) I do not own a nello anymore since the API has been shut down. I did not move this to community as well, since they is no official API support. I can change this as soon as the support is continued.
