### ISSUE TITLE
"Let Alexa inform you about door ring"-Skript funktioniert nicht

### ISSUE THREAD

**Issue by lasugle** [Zefau/ioBroker.nello#4]
Hallo. Zunächst erstmal vielen Dank für deine Bemühungen! Ich konnte den ioBroker Adapter für Nello erfolgreich einbinden und soweit funktioniert auch alles. Einzig das "Let Alexa inform you about door ring"-Skript funktioniert bei mir nicht. Wenn ich klingel kommt keine Sprachausgabe von Alexa. Ich vermute, dass der ioBroker das Klingelevent nicht vernünftig auslesen kann. Kann ich irgendwie ein LOG schreiben lassen, um zu überprüfen ob das Klingelevent erkannt wird? (Habe den ioBroker erst seit einer Woche am laufen) Die Function Say funktioniert übrigens. Ich habe nur mal die folgenden Zeilen ausgeführt und die Sprachrückgabe hat funktioniert!

```
var L = {
    'actionRingUnknown': 'Es hat an der Tür geklingelt!',
    'actionOpenName': '%name% hat die Tür geöffnet.',
    'actionOpen': 'Die Haustür wurde geöffnet.'
};
say(L.actionRingUnknown);
```

Es muss also an dem Rest liegen (#YOUR DOOR ID# wurde natürlich ersetzt):

```
on({id: 'nello.0.#YOUR DOOR ID#.events.feed', change: 'any'}, function(obj)
{
    var events = JSON.parse(obj.state.val);
    if (events.length === 0) return;
    
    var event = events[events.length-1];
    if (event.action == 'deny')
        say(L.actionRingUnknown);
    
    else if (event.action == 'swipe' || event.action == 'geo')
        say(L.actionOpenName.replace(/%name%/gi, event.data.name));
        
    else
        say(L.actionOpen);
});
```

**Comment by Zefau** [comment]
IoBroker hat links in der Navigation ein Log. In diesem findest du die Info, wenn jemand geklingelt hat bzw. eine Fehlermeldung.

Zum Auslesen der Events ist eine Port Weiterleitung notwendig. Diese hast du freigegeben?

**Comment by lasugle** [comment]
Danke für die schnelle Antwort. Den Punkt "Advanced Setup" habe ich tatsächlich übersehen. Besteht vielleicht die Möglichkeit eine Anleitung zu erstellen, wie man einen Webhook einrichtet? Ich bin leider ein ziemlicher Anfänger und habe es bis jetzt nicht hinbekommen. Was DynDNS bedeutet und wie man es einrichtet weiß ich allerdings. Danke im Voraus.

**Comment by Zefau** [comment]
Was fehlt dir denn konkret bei der aktuellen Anleitung? Dann weiß ich, was noch zu beschrieben ist.

Wenn du eine DynDNS Adresse hast passt das ja schon. Jetzt noch einen beliebigen Port auf deinem Router freischalten und auf ioBroker weiterleiten und die DynDNS Adresse und Port im Adapter hinterlegen.

Viele Grüße
Zefau

**Comment by lasugle** [comment]
Ich habe nun die DynDNS-Adresse in den Adapter eingegeben und der Port ist auch freigeschaltet und erreichbar. Leider taucht der Ordner Channels aber nicht in der Baumansicht von Nello auf :(
Im Log sieht alles gut aus:

![image](https://user-images.githubusercontent.com/45314103/48973118-867d6600-f038-11e8-96a6-2c285575a60f.png)

**Comment by Zefau** [comment]
Sieht gut aus. Klingel mal bei dir, dann sollten die state angelegt werden und Alexa sollte dir ansagen, dass es geklingelt hat.

**Comment by Zefau** [comment]
Und, funktioniert's? :-)

**Comment by lasugle** [comment]
Hallo. Mittlerweile funktioniert es tatsächlich! Gestern Nacht hat es noch nicht geklappt, aber als ich es gerade noch einmal versucht habe, hat mich Alexa darüber informiert, dass es an der Tür geklingelt hat. Danke für deine Hilfe! :)
