### ISSUE TITLE
Add adapter testing and activate travis-ci

### ISSUE THREAD

**Issue by Apollon77** [Zefau/ioBroker.nello#5]

**Comment by Zefau** [comment]
Adapter testing is already added and travis is successful. What is missing?

**Comment by Apollon77** [comment]
hhmmm ... my fork is not updatung from your master repo ... strange ... need to check that. Then ok :-)

**Comment by Zefau** [comment]
What's the fork for?

**Comment by Apollon77** [comment]
I have forked all Adapter and will provide updates for central files like adapter testing and utils as PR when there are changes. And so I have an overview about testing Status for all Adapters because I have them enabled in my Travis too.
