### ISSUE TITLE
Advanced Setup issue

### ISSUE THREAD

**Issue by jensfr1** [Zefau/ioBroker.nello#6]
Hello, 
I dont have any place in iobroker in the nello settings where I can add the DYNDNS URL? 
The only setting I can do is the generation of the token. Do I miss anything? 

Thanks  a lot,
Jens

**Comment by jensfr1** [comment]
delete.. my mistake

**Comment by Zefau** [comment]
Does it look like that? 

![](https://i.imgur.com/wD1HqUW.jpg)

**Comment by Zefau** [comment]
What version is installed?

**Comment by Zefau** [comment]
Ah, ok. Saw too late. Have fun.

**Comment by jensfr1** [comment]
I had to scroll a lot down to find the other menu settings. Didn't realize that initially.. ;)

**Comment by jensfr1** [comment]
![2018-12-10 12_12_22-greenshot image editor](https://user-images.githubusercontent.com/12272992/49729176-04ff1800-fc75-11e8-959b-362f9072c404.png)

**Comment by Zefau** [comment]
Was für einen Browser hast du denn?

**Comment by jensfr1** [comment]
Ganz normal Google Chrome. Ist auch an 2 Laptops so...

**Comment by Zefau** [comment]
Ich nutze Firefox, da habe ich das nicht. Ich gucke mir das am WE nochmal an. Ist nicht dringend aber trotzdem blöd. Danke für den Hinweis

**Comment by jensfr1** [comment]
Ok. Also das funktioniert soweit. Wenn es klingelt bekomme ich über Alexa eine Ansage. Ebenfalls wenn ich über die Nello App die Tür öffnen sagt Alexa was. Soweit so gut! 
Was nicht funktioniert ist das ich sagen kann Alexa, Tür öffnen. Skripte sehen soweit gut aus.

**Comment by Zefau** [comment]
Cloud adapter zeigt das Gerät an und Alexa findet es? Routine erstellt und Gerät zugewiesen?

**Comment by jensfr1** [comment]
Also die Tür wird unter Smart Geräte in ioBroker gefunden.  Tür öffnen Typ switch. 
Gerätsuche in Alexa findet das Gerät nicht....

**Comment by jensfr1** [comment]
Benötige Ich dazu iobroker.pro verbunden mit Alexa?

**Comment by Zefau** [comment]
IoBroker cloud oder iot, aber die free Version genügt.

**Comment by jensfr1** [comment]
Ja ok daran hats gelegen! Funktioniert bestens! Danke!

**Comment by Zefau** [comment]
Google chrome design issue addressed with https://github.com/Zefau/ioBroker.nello/commit/12833e117007e58f9d071d97bcf8b7630227d279
