### ISSUE TITLE
Question MQTT

### ISSUE THREAD

**Issue by jensfr1** [Zefau/ioBroker.nello#7]
Hello, 
I would like to know if there is a easy way to write the latest event feed into a mqtt object.  I am sure for a code it is not difficult. 

`[{"data":{"location_id":"Loc","name":"J","user_id":"USer","timestamp":1544444589},"action":"swipe"},
`
Thanks, Jens

**Comment by Zefau** [comment]
What's the purpose / objective of writing it into a mqtt object? And for my understanding: By mqtt object you mean a certain state within ioBroker objects (using `setState()`)?

Cheers, Zefau

**Comment by jensfr1** [comment]
Yes exactly. The purpose. I want to use it in node-red and then trigger some actions via Node-Red. Maybe there is a better option....?

**Comment by Zefau** [comment]
> var obj = getState('nello.0.86299b21-2c19-44b0-a53a-67fa4c09826a.events.feed');
> var feed = obj !== undefined && obj.val !== undefined ? JSON.parse(obj.val) : [];
> var last = feed[feed.length-1] || 'kein Event';
> //setState("##STATE##", last);

`setState` auskommentieren und `##STATE##` mit dem State ersetzen, das beschrieben werden soll.

**Comment by Zefau** [comment]
Does it work? Can we close the ticket?
